Config.Markers = {
	drawDistance = 15.0,
	garage = {
		width = 2.0,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
		blip = {
			sprite = 357,
			color = 2,
			scale = 0.8,
			label = "Garage",
			enable = true,
		},
	},
	weedProcessing = {
		width = 2.0,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
		blip = {
			sprite = 501,
			color = 35,
			scale = 0.8,
			label = "Weed Processing",
			enable = true,
		},
	},
	safeHouse = {
		width = 2.0,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
		blip = {
			sprite = 40,
			color = 0,
			scale = 0.8,
			label = "Safe House",
			enable = true,
		},
	},
	menu = {
		width = 2.0,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
		blip = {
			sprite = 40,
			color = 0,
			scale = 0.8,
			label = "Safe House",
			enable = true,
		},
	},
	enterIplMarker = {
		width = 2.0,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
		blip = {
			sprite = 40,
			color = 0,
			scale = 0.8,
			label = "Safe House",
			enable = true,
		},
	},
	warehouse = {
		width = 2.0,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
		blip = {
			sprite = 478,
			color = 3,
			scale = 0.8,
			label = "Warehouse",
			enable = true,
		},
	},
	enterMoneyLaundering = {
		width = 2.0,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
		blip = {
			sprite = 500,
			color = 35,
			scale = 0.8,
			label = "Money Laundering",
			enable = true,
		},
	},
	moneyLaundering = {
		width = 2.0,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
	},
	capture = {
		width = 75.0,
		height = 50.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 50 },
		type = 1,
	},
	exitIpl = {
		width = 1.5,
		height = 1.0,
		draw = true,
		color = { r = 0, g = 174, b = 255, a = 200 },
		type = 23,
	},
}